import {plusMinusButton} from "./scripts/plusMinusButton.js";
import {ckeditor} from "./scripts/ckeditor.js";
import {renderForm} from "./scripts/form.js";
import {closeElement} from "./scripts/closeElement.js";
import {renderTabs} from "./scripts/tabs.js";
import {savedChangesStatus} from "./scripts/savedChangesStatus.js";
import {events} from "./scripts/events.js";
import {faqs} from "./scripts/faqs.js";
import {renderProduct} from "./scripts/product.js";
import {menu} from "./scripts/menu.js";
import {renderCart} from "./scripts/cart.js";
import {checkout} from "./scripts/checkout.js";
import {fingerprint} from "./scripts/fingerprint.js";

plusMinusButton();
renderForm();
ckeditor();
closeElement();
renderTabs();
savedChangesStatus();
events();
faqs();
renderProduct();
menu();
renderCart();
checkout();
fingerprint();