require('../bootstrap');

import {ckeditor} from "./scripts/ckeditor.js";
import {menuButton} from "./scripts/menuButton.js";
import {tabs} from "./scripts/tabs.js";
import {localeTabs} from "./scripts/localeTabs.js";
import { cleanConfirmation } from "./scripts/cleanConfirmation.js";
import {renderForm} from "./scripts/form.js";
import { switchButton } from "./scripts/switchButton.js";
import {userModification} from "./scripts/userModification";
import {characterCounter} from "./scripts/characterCounter.js";
import {savedChangesStatus} from "./scripts/savedChangesStatus.js";
import {loadImage} from "./scripts/loadImage.js";
import {nestedSort} from "./scripts/nestedSort.js";
import {filter} from "./scripts/filter.js";
import {tooltip} from "./scripts/tooltip.js";
import {events} from "./scripts/events.js";
import {renderSelects} from "./scripts/renderSelects.js";
import {renderTable} from "./scripts/table.js";

ckeditor();
cleanConfirmation();
menuButton();
tabs();
localeTabs();
renderForm();
switchButton();
userModification();
characterCounter();
savedChangesStatus();
loadImage();
nestedSort();
filter();
tooltip();
events();
renderSelects();
renderTable();